version: '3.6'

services:

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: express
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: books_store
    ports:
      - "3306:3306"

  mysql_test:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: express
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test_books_store
    ports:
      - "3307:3306"  

  app:
    build: .
    depends_on:
      - mysql
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      bash -c "./wait-for-it.sh mysql:3306 &&
      node_modules/.bin/sequelize db:migrate &&
      npm start"